
import About from '@/components/About'
import React from 'react'

export const metadata = {
    title: "About",
    description: "Generated by create next app",
  };

const page = () => {
    

    return (
        <div>
           <About />
        </div>
    )
}

export default page
